# Generated by Django 6.0.5 on 2026-06-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
