# Generated by Django 6.0.5 on 2026-05-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_charge_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='order',
            name='api_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remains',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='provider_service_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Partial', 'Partial'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_qty',
            field=models.IntegerField(),
        ),
    ]
