# Generated by Django 6.0.5 on 2026-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_remove_service_provider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider_service_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
